/* eslint-disable @typescript-eslint/no-unused-vars */

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="container mx-auto mt-4 mb-12 max-w-screen-xl">
          {children}
        </main>
      </body>
    </html>
  );
}
